[phases.setup]
cmds = [
    "curl https://sh.rustup.rs -sSf | sh -s -- -y",
    "source $HOME/.cargo/env"
]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/dilithium-webapp"